-- 1.List all orders along with the customer name, store name, and employee who handled the order.
SELECT 
    o.OrderID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    s.StoreName,
    CONCAT(e.FirstName, ' ', e.LastName) AS EmployeeName
FROM
    orders o
        JOIN
    customers c ON o.CustomerID = c.CustomerID
        JOIN
    employees e ON o.EmployeeID = e.EmployeeID
        JOIN
    stores s ON o.StoreID = s.StoreID;
    
-- 2.Show each product sold along with its category and the total quantity sold. 
SELECT 
    p.ProductName,
    p.CategoryID,
    SUM(od.Quantity) AS Total_Quantity_sold,
    c.CategoryName
FROM
    order_details od
        JOIN
    products p ON od.ProductID = p.ProductID
        JOIN
    categories c ON p.CategoryID = c.CategoryID
GROUP BY p.ProductID;


-- 3.List all customers who have placed at least one order, showing their orders and total spent.
SELECT 
    o.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    SUM(o.TotalAmount) AS Total_spent
FROM
    orders o
        JOIN
    customers c ON o.CustomerID = c.CustomerID
GROUP BY c.CustomerID;

-- 4.Identify orders where the employee’s store is different from the store where the order was placed.
SELECT 
    o.OrderID,
    o.EmployeeID,
    o.StoreID AS Order_Store,
    e.StoreID AS Employee_store
FROM
    orders o
        JOIN
    employees e ON o.EmployeeID = e.EmployeeID
WHERE
    o.storeID != e.StoreID;


-- 5.Show the top 10 customers by total spending across all orders.
SELECT 
    CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName,
    o.customerID,
    SUM(o.totalamount) AS total_spent
FROM
    orders o
        JOIN
    customers c ON o.customerID = c.customerID
GROUP BY o.customerID , customername
ORDER BY total_spent DESC
LIMIT 10;


-- 6.Calculate total revenue generated by each store.
SELECT 
    storeID, SUM(totalamount) AS total_revenue
FROM
    orders
GROUP BY storeID;

-- 7.Find the average order value per store.
SELECT 
    storeID, AVG(totalamount) AS avg_order_value
FROM
    orders
GROUP BY storeID;

-- 8.Determine total revenue per product category.
SELECT 
    c.categoryID,
    CategoryName,
    SUM(quantity * unitprice) AS category_revenue
FROM
    categories c
        JOIN
    products p ON c.categoryID = p.categoryID
        JOIN
    order_details od ON p.productID = od.productID
GROUP BY c.categoryID , categoryname;

-- 9.Identify the top 5 best-selling products by quantity sold.
SELECT 
    p.productid,
    p.productname,
    p.categoryid,
    SUM(quantity) AS total_quantity
FROM
    products p
        JOIN
    order_details od ON p.productid = od.productid
GROUP BY p.productid , p.productname , p.categoryid
ORDER BY total_quantity DESC LIMIT 5;


-- 10.Calculate the average discount applied per product across all orders.
SELECT 
    productid,
    SUM(quantity) AS total_product_sold,
    sum(discount*quantity)/sum(quantity) AS avg_discount_per_product
FROM
    order_details
GROUP BY productid;


-- 11.Identify customers who have placed more than 5 orders.
SELECT 
    c.customerid,
    CONCAT(c.firstname, ' ', c.lastname) AS customername,
    COUNT(o.orderid) AS order_count
FROM
    orders o
        JOIN
    customers c ON o.customerid = c.customerid
GROUP BY c.customerid , customername
HAVING order_count > 5;

-- 12.Find the top 10 customers with the highest lifetime spending.
SELECT 
    c.customerid,
    CONCAT(c.firstname, ' ', c.lastname) AS customername,
    COUNT(o.orderid) order_count,
    SUM(totalamount) AS lifetime_spending
FROM
    customers c
        JOIN
    orders o ON c.customerId = o.customerid
GROUP BY c.customerid, customername
ORDER BY lifetime_spending DESC
LIMIT 10;


-- 13.Calculate the average order value for each customer.
WITH customer_totals AS
	(SELECT 
		c.customerid,
		CONCAT(c.firstname, ' ', c.lastname) AS customername,
		COUNT(o.orderid) order_count,
		SUM(totalamount) AS lifetime_spending
	FROM
		customers c
			JOIN
		orders o ON c.customerId = o.customerid
	GROUP BY c.customerid
)

SELECT 
	customerid, 
	customername,
	order_count, 
	lifetime_spending,
	lifetime_spending/ order_count AS avg_order_value
from customer_totals;


-- 14.List customers who have placed orders in more than one store.
SELECT 
    c.customerid,
    c.firstname,
    c.lastname,
    COUNT(DISTINCT o.storeid) AS stores_visited
FROM
    customers c
        JOIN
    orders o ON c.customerid = o.customerid
GROUP BY c.customerid , c.firstname , c.lastname
HAVING stores_visited > 1;

-- 15.Calculate the percentage of customers who have placed only one order.
WITH customer_summary AS(
	SELECT 
		c.customerid,
		COUNT(o.orderid) AS order_count
	FROM
		customers c
			LEFT JOIN
		orders o ON c.customerid = o.customerid
	GROUP BY c.customerid
	HAVING order_count = 1)

    
SELECT 
	COUNT(customerid)*100/ (SELECT COUNT(customerid) FROM customers)
	AS percent_one_time_orderers 
FROM customer_summary;

-- 16.Identify the top 3 revenue-generating products in each category.
WITH category_totals AS(	
    SELECT 
		c.categoryid,
		c.categoryname,
		p.productid,
		p.productname,
		SUM(od.quantity * od.unitprice * (1 - od.discount / 100)) AS total_revenue,
		rank() over(partition by c.CategoryID order by SUM(od.quantity * od.unitprice * (1 - od.discount / 100)) desc) as rank_in_cat
	FROM
		products p
			JOIN
		order_details od ON p.productid = od.productid
			JOIN
		categories c ON p.categoryid = c.categoryid
			JOIN
		orders o ON o.orderid = od.orderid
	GROUP BY p.productid
	)

SELECT * FROM category_totals 
WHERE rank_in_cat <=3;

-- 17.Find products that have never been sold.
SELECT 
    p.productid,
    p.productname,
    COUNT(od.productid) AS order_count
FROM
    products p
        LEFT JOIN
    order_details od ON p.productid = od.productid
GROUP BY p.productid , p.productname
having order_count= 0;


-- 18.Calculate total revenue generated per product.
SELECT 
    p.productid,
    p.productname,
    SUM(od.quantity) AS quantity_sold,
    ROUND(SUM(od.unitprice * od.quantity * (1 - od.discount / 100)),
            2) AS total_product_revenue
FROM
    products p
        JOIN
    order_details od ON p.productid = od.productid
GROUP BY p.productid , p.productname;


-- 19.Determine the average quantity sold per order for each product.
SELECT 
    od.productID,
    COUNT(o.orderId) AS order_count,
    SUM(od.quantity) AS total_units_sold,
    ROUND(SUM(od.quantity) / COUNT(o.orderID), 2) AS avg_quantity_sold_per_order
FROM
    orders o
        JOIN
    order_details od ON o.orderID = od.orderID
GROUP BY od.productID;

-- 20.Identify products with total sales revenue greater than the average product revenue.
WITH total_revenue AS (
	SELECT
		productID,
		round(sum(quantity * unitprice * (1-discount/100)), 2) AS product_revenue,
		AVG(sum(quantity * unitprice * (1-discount/100))) OVER () AS avg_revenue
	FROM order_details
	GROUP BY productID
    )
    
 SELECT
	productID,
    product_revenue,
    avg_revenue
FROM total_revenue
WHERE product_revenue > avg_revenue;

-- 21.Calculate total sales handled by each employee.
SELECT 
    o.employeeID,
    CONCAT(e.FirstName, ' ', e.LastName) AS employee_name,
    SUM(o.totalamount) AS total_sales_handeled
FROM
    order_details od
        JOIN
    orders o ON od.orderID = o.orderID
        JOIN
    employees e ON o.employeeID = e.employeeID
GROUP BY e.employeeID;

-- 22.Identify the top 5 employees who generated the highest revenue.
SELECT 
    o.employeeID,
    CONCAT(e.FirstName, ' ', e.LastName) AS employee_name,
    SUM(o.totalamount) AS total_sales_handeled
FROM
    order_details od
        JOIN
    orders o ON od.orderID = o.orderID
        JOIN
    employees e ON o.employeeID = e.employeeID
GROUP BY e.employeeID
ORDER BY SUM(o.totalamount) DESC
LIMIT 5;

-- 23.Determine the average order value handled by each employee.
SELECT 
    e.employeeID,
    CONCAT(e.FirstName, ' ', e.LastName) AS employee_name,
    ROUND(AVG(o.totalamount), 2) AS avg_order_value_handled
FROM
    employees e
        JOIN
    orders o ON e.employeeID = o.employeeID
GROUP BY e.employeeID;

-- 24.Find employees who handled orders for more than 40 unique customers.
SELECT 
    o.employeeID,
    CONCAT(e.FirstName, ' ', e.LastName) AS employee_name,
    COUNT(DISTINCT o.customerID) AS unique_customers
FROM
    employees e
        JOIN
    orders o ON e.employeeID = o.employeeID
GROUP BY o.employeeID , employee_name
HAVING unique_customers > 40;
    
-- 25.Identify the employee with the highest total quantity of products sold.
WITH emp_units_sold AS(
    SELECT 
		o.employeeID,
		CONCAT(e.FirstName, ' ', e.LastName) AS employee_name,
		SUM(od.quantity) AS units_sold
	FROM
		employees e
			JOIN
		orders o ON e.employeeID = o.employeeID
			JOIN
		order_details od ON o.orderID = od.OrderID
	GROUP BY o.employeeID
)

SELECT 
	employeeID, 
    employee_name, 
    units_sold 
FROM emp_units_sold
WHERE units_sold = (SELECT max(units_sold) FROM emp_units_sold);

-- 26.Calculate monthly revenue trends across all stores. 
SELECT 
    YEAR(orderdate) AS sale_year,
    MONTH(orderdate) AS sale_month,
    SUM(totalamount) AS revenue
FROM
    orders
GROUP BY sale_year , sale_month
ORDER BY sale_year , sale_month;

-- 27.Determine the store with the highest sales for each month.
WITH monthly_totals AS(	
    SELECT 
		YEAR(o.orderdate) AS sale_year,
		MONTH(o.orderdate) AS sale_month,
		o.storeID,
		s.storename,
		SUM(o.totalamount) AS revenue,
        RANK() OVER (PARTITION BY YEAR(o.orderdate), 
			MONTH(o.orderdate)
			ORDER BY SUM(o.totalamount) DESC) AS monthly_rank
	FROM
		orders o
			JOIN
		stores s ON o.storeID = s.storeID
	GROUP BY sale_year , sale_month , o.storeID , s.storename
)

SELECT 
	sale_year, 
    sale_month, 
    storeID, 
    storename, 
    revenue, 
    monthly_rank
FROM monthly_totals
WHERE monthly_rank = 1;


-- 28.Identify the top selling product each month.
WITH monthly_sales_quantity AS(	
    SELECT 
		YEAR(o.orderdate) AS sale_year,
		MONTH(o.orderdate) AS sale_month,
		p.productID,
		p.productname,
		SUM(od.quantity) AS units_sold,
		RANK() OVER(PARTITION BY YEAR(o.orderdate), MONTH(o.orderdate)
		ORDER BY SUM(od.quantity) DESC) AS monthly_rank
	FROM
		orders o
			JOIN
		order_details od ON o.orderID = od.orderID
			JOIN
		products p ON od.productID = p.productID
	GROUP BY sale_year , sale_month , p.productID , p.productname
)

SELECT 
	sale_year, 
    sale_month, 
    productID, 
    productname, 
    units_sold, 
    monthly_rank
FROM monthly_sales_quantity
WHERE monthly_rank = 1;

-- 29.Calculate the daily average number of orders.
WITH daily_order_count AS(	
    SELECT 
		orderdate, COUNT(*) AS daily_order
	FROM
		orders
	GROUP BY orderdate
)

SELECT 
	ROUND(AVG(daily_order), 2) AS avg_order_per_day
FROM daily_order_count;

-- 30.Find the month with the highest total revenue.
WITH monthly_revenue AS(	
    SELECT 
		YEAR(orderdate) AS sale_year,
		MONTH(orderdate) AS sale_month,
		SUM(totalamount) AS revenue
	FROM
		orders
	GROUP BY sale_year , sale_month
)

SELECT 
	sale_year,
    sale_month,
    revenue
FROM monthly_revenue
WHERE revenue = (SELECT 
                    MAX(revenue) 
                    FROM 
                    monthly_revenue
);
